name: Build

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2

        - name: create file list
          id: files_list
          run: |
            echo "files=$(printf '"%s" ' **/*.md)" > $GITHUB_OUTPUT

        - uses: docker://pandoc/core:3.0.1
          with:
            args: -f markdown+rebase_relative_paths+gfm_auto_identifiers --toc -s -t gfm ${{ steps.files_list.outputs.files }} -o output.md 